import type { Metadata } from "next";
import { ArrowUpRight, Box, GitPullRequest, PackageOpen } from "lucide-react";

export const metadata:Metadata={title:"Packages",description:"Open Pentool libraries published through public GitHub pull requests."};
type Package={name:string;version:string;description:string;license?:string;repository?:string;authors:string[];pentool?:string;assets:number;hash:string;path:string};
const catalogUrl="https://agkomyint.github.io/pentool-registry/registry/catalog.json";
const registryRepo="https://github.com/agkomyint/pentool-registry";
async function getPackages():Promise<Package[]>{try{const response=await fetch(catalogUrl,{next:{revalidate:300}});if(!response.ok)return[];const catalog=await response.json() as {packages?:Package[]};return catalog.packages??[]}catch{return[]}}

export default async function PackagesPage(){const packages=await getPackages();return <main><section className="border-b hairline"><div className="shell grid gap-10 py-20 lg:grid-cols-[1fr_.7fr] lg:items-end"><div><p className="label text-[var(--muted)]">Community registry</p><h1 className="display mt-5 max-w-4xl text-6xl md:text-8xl">Packages, reviewed in public.</h1><p className="mt-7 max-w-2xl text-xl leading-8 text-[var(--muted)]">No registry accounts and no private publishing API. Every library arrives through a GitHub pull request, passes automated verification, and remains mirrorable.</p></div><div className="rounded-xl bg-[var(--ink)] p-6 text-white"><p className="label text-white/40">Registry URL</p><code className="mt-4 block break-all text-sm text-[var(--signal)] mono">https://agkomyint.github.io/pentool-registry/registry</code></div></div></section>
<section className="shell py-16">{packages.length?<div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{packages.map(pkg=><article key={`${pkg.name}@${pkg.version}`} className="lift flex min-h-64 flex-col rounded-xl border hairline bg-white/35 p-6"><div className="flex items-center justify-between"><PackageOpen size={22}/><span className="rounded-full bg-[var(--signal)] px-2.5 py-1 text-xs mono">v{pkg.version}</span></div><h2 className="mt-10 text-2xl font-semibold tracking-[-.045em]">{pkg.name}</h2><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{pkg.description||"Open Pentool design package."}</p><div className="mt-auto flex items-center justify-between pt-6 text-xs text-[var(--muted)]"><span>{pkg.assets} assets</span><span>{pkg.license??"License declared in package"}</span></div></article>)}</div>:<div className="grid min-h-[430px] place-items-center rounded-2xl border border-dashed border-[var(--muted)]/50 bg-white/20 p-8 text-center"><div className="max-w-xl"><Box className="mx-auto text-[var(--muted)]" size={34}/><h2 className="mt-6 text-4xl font-semibold tracking-[-.05em]">The shelf is ready.</h2><p className="mt-4 text-[var(--muted)]">Be the first to publish an open Pentool library. Build a <code className="mono">.penpkg</code>, add it to the public registry, and open a pull request.</p><a href={registryRepo} className="mt-8 inline-flex items-center gap-2 rounded-md bg-[var(--signal)] px-5 py-3.5 text-sm font-semibold"><GitPullRequest size={17}/> Publish with a PR <ArrowUpRight size={16}/></a></div></div>}</section>
<section className="border-t hairline bg-[var(--paper-2)]"><div className="shell grid gap-8 py-14 md:grid-cols-3"><Principle title="No account" text="GitHub identity and pull-request history provide the contribution trail."/><Principle title="No backend" text="The index and package files are static, immutable, and CDN-friendly."/><Principle title="No lock-in" text="Clone the repository or point Pentool at any compatible mirror."/></div></section></main>}
function Principle({title,text}:{title:string;text:string}){return <div><p className="label">{title}</p><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{text}</p></div>}
