import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Box, Braces, Layers3, PackageOpen, Terminal, Users } from "lucide-react";
import { CopyCommand } from "@/components/copy-command";
const repo="https://github.com/agkomyint/pentoolgg";
const features=[
  {icon:Terminal,title:"One native binary",text:"Serve the editor, automate drawings, inspect files, and export PNG or SVG without a Node stack."},
  {icon:Braces,title:"Readable by default",text:"Every .pen document is structured JSON: pages, layers, paths, text, fonts, and stable IDs included."},
  {icon:Users,title:"Human + agent",text:"Agents use precise CLI commands. Humans open the same file in a visual browser canvas. Nobody gets a flattened artifact."},
  {icon:PackageOpen,title:"Open packages",text:"Pack, sign, publish, mirror, and install design libraries with the host-independent .penpkg protocol."},
];
export default function Home(){return <main>
  <section className="relative overflow-hidden border-b hairline"><div className="pointer-events-none absolute inset-0 grid-paper opacity-60"/><div className="shell relative grid min-h-[760px] items-center gap-12 py-20 lg:grid-cols-[1.05fr_.95fr] lg:py-24"><div><div className="label mb-7 flex items-center gap-3"><span className="size-2 rounded-full bg-[var(--signal)] ring-4 ring-[#b8f34a]/25"/> Open-source vector infrastructure</div><h1 className="display max-w-4xl text-[clamp(4rem,9vw,8.2rem)]">Design is a file again.</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-[var(--muted)] md:text-xl">Pentool is a vector editor built for humans and agents. Draw through the CLI, refine in the browser, and ship editable work as open <code className="mono text-[.9em] text-[var(--ink)]">.pen</code> files.</p><div className="mt-9 flex flex-wrap gap-3"><a href={`${repo}/releases`} className="lift inline-flex items-center gap-2 rounded-md bg-[var(--ink)] px-5 py-3.5 text-sm font-semibold text-white">Download Pentool <ArrowRight size={16}/></a><Link href="/docs" className="inline-flex items-center rounded-md border hairline bg-[var(--paper)] px-5 py-3.5 text-sm font-semibold hover:bg-white">Read the docs</Link></div><div className="mt-8 max-w-xl"><CopyCommand command="pentool serve"/><p className="mt-3 text-xs text-[var(--muted)]">Then open <span className="mono">127.0.0.1:4711</span>. No database. No account. No cloud required.</p></div></div>
  <div className="relative mx-auto w-full max-w-[550px]"><div className="absolute -inset-6 rotate-3 rounded-[32px] bg-[var(--signal)]"/><div className="relative overflow-hidden rounded-2xl border-2 border-[var(--ink)] bg-[#17191f] shadow-[16px_16px_0_#111318]"><div className="flex h-11 items-center gap-2 border-b border-white/10 px-4"><span className="size-2.5 rounded-full bg-[#ff6b5e]"/><span className="size-2.5 rounded-full bg-[#ffc547]"/><span className="size-2.5 rounded-full bg-[var(--signal)]"/><span className="ml-auto text-[10px] text-white/35 mono">poster.pen</span></div><div className="grid min-h-[420px] grid-cols-[84px_1fr]"><div className="border-r border-white/10 p-3 text-[9px] text-white/45 mono"><p className="text-white">LAYERS</p><p className="mt-4">▾ hero</p><p className="pl-2">◇ nib</p><p className="pl-2">T title</p><p className="mt-3">▸ footer</p></div><div className="grid-paper relative grid place-items-center bg-[#f4f3ec] p-8"><div className="relative grid aspect-[4/3] w-full place-items-center overflow-hidden border-2 border-[#111318] bg-[#b8f34a]"><Image src="/brand/pentool-icon.svg" width={170} height={170} alt="Pentool pen nib mark" className="drop-shadow-[8px_8px_0_rgba(17,19,24,.18)]"/><span className="absolute bottom-4 right-4 rounded bg-[#111318] px-2 py-1 text-[9px] text-white mono">editable • 4 layers</span></div></div></div></div></div></div></section>
  <section className="border-b hairline bg-[var(--signal)]"><div className="shell flex flex-wrap items-center justify-between gap-5 py-6"><p className="text-xl font-semibold tracking-[-.03em]">One workflow. Two collaborators.</p><div className="flex flex-wrap gap-7 text-xs font-semibold uppercase tracking-wider"><span>CLI precision</span><span>Visual editing</span><span>Open files</span></div></div></section>
  <section className="shell py-24"><div className="mb-12 grid gap-4 md:grid-cols-2"><div><p className="label text-[var(--muted)]">Why Pentool</p><h2 className="display mt-4 text-5xl md:text-7xl">The whole design stays yours.</h2></div><p className="max-w-lg self-end text-lg leading-8 text-[var(--muted)]">No proprietary canvas hiding behind an API. Pentool makes the document format, renderer, automation surface, and package protocol part of the same open system.</p></div><div className="grid border-l border-t hairline md:grid-cols-2 lg:grid-cols-4">{features.map(({icon:Icon,title,text},i)=><article key={title} className="min-h-72 border-b border-r hairline p-6"><span className="mono text-xs text-[var(--muted)]">0{i+1}</span><Icon className="mt-12" size={28}/><h3 className="mt-5 text-xl font-semibold tracking-[-.035em]">{title}</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{text}</p></article>)}</div></section>
  <section className="border-y hairline bg-[var(--paper-2)] py-24"><div className="shell"><p className="label text-[var(--muted)]">From prompt to pixels</p><div className="mt-8 grid gap-5 lg:grid-cols-[.85fr_1.15fr]"><div className="rounded-xl bg-[var(--ink)] p-7 text-white"><div className="flex items-center gap-2 text-xs text-white/45 mono"><Terminal size={14}/> terminal</div><pre className="mt-10 overflow-x-auto text-sm leading-8 text-white/80 mono"><span className="text-[var(--signal)]">$</span> pentool new poster.pen --width 1200 --height 800{"\n"}<span className="text-[var(--signal)]">$</span> pentool rect poster.pen card 80 80 520 640{"\n"}<span className="text-[var(--signal)]">$</span> pentool text poster.pen title &quot;Open by design&quot; 120 160{"\n"}<span className="text-[var(--signal)]">$</span> pentool export poster.pen poster.svg</pre><div className="mt-10 flex gap-3 text-xs text-white/45"><Layers3 size={16}/><span>Every command preserves structure.</span></div></div><div className="grid grid-cols-2 gap-5"><Showcase src="/showcase/eye.png" alt="An illustrated eye made with Pentool" label="Paths + layers"/><Showcase src="/showcase/cake.png" alt="A cake illustration made with Pentool" label="Made by an agent"/></div></div></div></section>
  <section className="shell py-24"><div className="grid gap-10 rounded-2xl bg-[var(--ink)] p-8 text-white md:p-14 lg:grid-cols-[1fr_.85fr]"><div><Box className="text-[var(--signal)]"/><h2 className="display mt-8 text-5xl md:text-7xl">Libraries without lock-in.</h2><p className="mt-6 max-w-xl text-lg leading-8 text-white/60">Any document, page, layer, object list, or selection can become a reusable asset. Publish deterministic <code className="mono text-[var(--signal)]">.penpkg</code> archives to GitHub Releases, static storage, or your own registry.</p><Link href="/guides/libraries" className="mt-8 inline-flex items-center gap-2 text-sm font-semibold text-[var(--signal)]">Explore the package system <ArrowRight size={16}/></Link></div><div className="self-center rounded-lg border border-white/10 bg-black/30 p-5 text-xs leading-7 text-white/70 mono"><span className="text-[#7d838e]"># build and verify</span><br/><span className="text-[var(--signal)]">$</span> pentool package pack ./open-ui<br/><span className="text-[var(--signal)]">$</span> pentool package verify open-ui.penpkg<br/><br/><span className="text-[#7d838e]"># publish anywhere</span><br/><span className="text-[var(--signal)]">$</span> pentool package publish open-ui.penpkg<br/><br/><span className="text-[#7d838e]"># install reproducibly</span><br/><span className="text-[var(--signal)]">$</span> pentool package install open-design/ui@0.1.0</div></div></section>
  <section className="border-t hairline"><div className="shell flex flex-col items-start justify-between gap-8 py-20 md:flex-row md:items-end"><div><p className="label text-[var(--muted)]">Ready when you are</p><h2 className="display mt-4 max-w-3xl text-5xl md:text-7xl">Make something everyone can open.</h2></div><a href={`${repo}/releases`} className="lift inline-flex shrink-0 items-center gap-2 rounded-md bg-[var(--signal)] px-6 py-4 font-semibold">Get Pentool <ArrowRight size={17}/></a></div></section>
</main>}
function Showcase({src,alt,label}:{src:string;alt:string;label:string}){return <figure className="lift overflow-hidden rounded-xl border hairline bg-[var(--paper)]"><div className="aspect-square p-3"><Image src={src} alt={alt} width={600} height={600} className="size-full rounded-lg object-cover"/></div><figcaption className="flex items-center justify-between border-t hairline px-4 py-3 text-xs"><span>{label}</span><span className="mono text-[var(--muted)]">.pen</span></figcaption></figure>}
